//
//  TakeCrypto.swift
//  CatchlightCore
//
//  Per-item Take encryption (Encryption Architecture §10, Phase 5 brief §5.4).
//
//  Each Take is sealed with AES-256-GCM under a key UNIQUE TO THAT TAKE, derived
//  on demand from the master key via HKDF-SHA-256:
//
//      itemKey = HKDF(
//          IKM  = masterKey,
//          salt = "catchlight-item-key",
//          info = <take.id.uuidString>,
//          L    = 32
//      )
//
//  The per-item key is ephemeral — never stored, never cached beyond the immediate
//  operation. CryptoKit's `AES.GCM.seal` generates a fresh random 12-byte nonce
//  per call and embeds it in `combined`; nonces are NEVER generated or reused
//  manually.
//
//  This file exposes three layers:
//    1. `CryptoService` — generic `encrypt(_:key:)` / `decrypt(_:key:)` over
//       AES-256-GCM, the canonical Apple-native AEAD primitives for this app.
//    2. `itemKey(masterKey:takeUUID:)` — the per-item HKDF derivation.
//    3. `encryptTake(...)` / `decryptTake(...)` and `TakeCrypto` — the
//       Take-specific wrapper (Take ⇄ JSON ⇄ AES-GCM ciphertext).
//

import Foundation
import CryptoKit

// MARK: - CryptoService (generic AES-256-GCM)

/// Apple-native AES-256-GCM primitives. The cipher is `CryptoKit.AES.GCM`; the
/// nonce is generated by CryptoKit and embedded in the returned `combined` blob
/// (12-byte nonce ‖ ciphertext ‖ 16-byte tag). Callers MUST NOT manage nonces.
public enum CryptoService {

    /// Seal `plaintext` under `key` using AES-256-GCM. Returns the combined form
    /// (nonce ‖ ciphertext ‖ tag).
    public static func encrypt(_ plaintext: Data, key: SymmetricKey) throws -> Data {
        let sealed = try AES.GCM.seal(plaintext, using: key)
        guard let combined = sealed.combined else {
            // `combined` is non-nil for the standard 12-byte nonce path used by
            // `AES.GCM.seal(_:using:)`. Surface defensively if a future API change
            // ever returns nil.
            throw CryptoError.malformedCiphertext
        }
        return combined
    }

    /// Open a `combined` AES-GCM blob under `key`. Throws
    /// `CryptoError.authenticationFailed` on tag failure (tampering, corruption,
    /// or wrong key); `CryptoError.malformedCiphertext` for a structurally bad
    /// blob. The plaintext is never returned on AEAD failure.
    public static func decrypt(_ combined: Data, key: SymmetricKey) throws -> Data {
        let box: AES.GCM.SealedBox
        do {
            box = try AES.GCM.SealedBox(combined: combined)
        } catch {
            throw CryptoError.malformedCiphertext
        }
        do {
            return try AES.GCM.open(box, using: key)
        } catch {
            throw CryptoError.authenticationFailed
        }
    }
}

// MARK: - Per-item key derivation (Phase 5 brief §5.4 / Encryption Architecture §10)

/// Derive the per-item AES-256-GCM key for a given Take. The master key is the
/// HKDF IKM; the Take's UUID string is the HKDF `info`; the fixed domain salt
/// `ItemKeyDerivationConstants.salt` provides cross-purpose key separation.
///
/// The key is ephemeral: the caller is expected to use it immediately and let it
/// fall out of scope. It is NEVER persisted or cached.
public func itemKey(masterKey: SymmetricKey, takeUUID: UUID) -> SymmetricKey {
    return HKDF<SHA256>.deriveKey(
        inputKeyMaterial: masterKey,
        salt: Data(ItemKeyDerivationConstants.salt.utf8),
        info: Data(takeUUID.uuidString.utf8),
        outputByteCount: ItemKeyDerivationConstants.outputByteCount
    )
}

/// Seal a Take payload under its per-item key. Returns the AES-256-GCM combined
/// form (12-byte nonce ‖ ciphertext ‖ 16-byte tag).
public func encryptTake(_ plaintext: Data, masterKey: SymmetricKey, takeUUID: UUID) throws -> Data {
    let key = itemKey(masterKey: masterKey, takeUUID: takeUUID)
    return try CryptoService.encrypt(plaintext, key: key)
}

/// Open a Take payload sealed by `encryptTake`. Throws
/// `CryptoError.authenticationFailed` if the blob has been tampered with, the
/// wrong key was used, or the wrong UUID was provided (the UUID is part of the
/// key derivation, so a UUID mismatch surfaces as an AEAD authentication
/// failure).
public func decryptTake(_ combined: Data, masterKey: SymmetricKey, takeUUID: UUID) throws -> Data {
    let key = itemKey(masterKey: masterKey, takeUUID: takeUUID)
    return try CryptoService.decrypt(combined, key: key)
}

// MARK: - Payload-level wrapper

/// Encrypts and decrypts whole `Take` values: Take ⇄ platform-agnostic JSON ⇄
/// AES-256-GCM ciphertext. The entire payload is encrypted (body text, all type
/// flags, reminder, completion, checklist, attachments, timestamps, sequence
/// membership) — everything except the Take's `id`, which is the HKDF `info`
/// input and must be known before decryption (Encryption Architecture §10.5).
public struct TakeCrypto: Sendable {
    private let keys: KeyHierarchy

    public init(keys: KeyHierarchy) {
        self.keys = keys
    }

    /// Serialise the Take to platform-agnostic JSON, then seal it under its
    /// per-item AES-256-GCM key.
    public func seal(_ take: Take) throws -> Data {
        let plaintext = try PlatformJSON.encode(take)
        return try encryptTake(plaintext, masterKey: keys.masterKey, takeUUID: take.id)
    }

    /// Open a sealed blob for a known Take UUID and decode it back to a Take.
    /// - Throws: `CryptoError.authenticationFailed` if the blob was tampered with.
    public func open(_ combined: Data, takeUUID: UUID) throws -> Take {
        let plaintext = try decryptTake(combined, masterKey: keys.masterKey, takeUUID: takeUUID)
        return try PlatformJSON.decode(Take.self, from: plaintext)
    }
}
